2024-01-03 17:26:23,971 INFO Started with the following arguments: {'data_name': 'gear_signals', 'seq_len': 2560, 'module': 'gru', 'hidden_dim': 24, 'num_layer': 3, 'iteration': 1, 'batch_size': 128, 'metric_iteration': 1, 'logfile': 'timegan.log', 'feature_number': 'Feat3', 'dataset_percentage': 5}
2024-01-03 17:26:23,994 INFO gear_signals dataset is ready.
2024-01-03 17:26:35.955036: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2024-01-03 17:26:36.024488: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla V100-SXM2-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:8a:00.0
2024-01-03 17:26:36.026382: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2024-01-03 17:26:36.029106: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2024-01-03 17:26:36.031265: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2024-01-03 17:26:36.032622: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2024-01-03 17:26:36.035867: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2024-01-03 17:26:36.038076: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2024-01-03 17:26:36.042886: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2024-01-03 17:26:36.043925: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2024-01-03 17:26:36.044336: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2024-01-03 17:26:36.053025: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2195035000 Hz
2024-01-03 17:26:36.053208: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55e2de1057f0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2024-01-03 17:26:36.053256: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2024-01-03 17:26:36.238445: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55e2dcfc1f20 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2024-01-03 17:26:36.238627: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Tesla V100-SXM2-32GB, Compute Capability 7.0
2024-01-03 17:26:36.239245: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: Tesla V100-SXM2-32GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:8a:00.0
2024-01-03 17:26:36.239352: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2024-01-03 17:26:36.239405: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2024-01-03 17:26:36.239453: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
2024-01-03 17:26:36.239500: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
2024-01-03 17:26:36.239547: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
2024-01-03 17:26:36.239593: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
2024-01-03 17:26:36.239641: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2024-01-03 17:26:36.240547: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2024-01-03 17:26:36.240672: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2024-01-03 17:26:36.241223: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2024-01-03 17:26:36.241321: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2024-01-03 17:26:36.241360: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2024-01-03 17:26:36.242558: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30581 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-32GB, pci bus id: 0000:8a:00.0, compute capability: 7.0)
2024-01-03 17:26:38,136 INFO Loading model from models/timegan_joint-1
2024-01-03 17:26:38,945 INFO Start Embedding Network Training
2024-01-03 17:26:39.862820: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
2024-01-03 17:26:48,099 INFO step: 0/1, e_loss: 0.1267
2024-01-03 17:26:49,438 INFO Finish Embedding Network Training
2024-01-03 17:26:49,438 INFO Start Training with Supervised Loss Only
2024-01-03 17:26:54,682 INFO step: 0/1, s_loss: 0.0393
2024-01-03 17:26:55,402 INFO Finish Training with Supervised Loss Only
2024-01-03 17:26:55,402 INFO Start Joint Training
2024-01-03 17:28:35,460 INFO step: 0/1, d_loss: 1.9152, g_loss_u: 1.0693, g_loss_s: 0.0321, g_loss_v: 0.1327, e_loss_t0: 0.1251
2024-01-03 17:28:36,226 INFO Finish Joint Training
2024-01-03 17:28:36,909 INFO after training
2024-01-03 17:28:36,909 INFO after random generator
Traceback (most recent call last):
  File "/scratch/lustre/home/dopu7482/miniconda3/envs/kursinis/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/scratch/lustre/home/dopu7482/miniconda3/envs/kursinis/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/scratch/lustre/home/dopu7482/miniconda3/envs/kursinis/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: assertion failed: [Expected shape for Tensor generator/rnn/sequence_length:0 is ] [1] [ but saw shape: ] [10240]
	 [[{{node generator/rnn/Assert/Assert}}]]
  (1) Invalid argument: assertion failed: [Expected shape for Tensor generator/rnn/sequence_length:0 is ] [1] [ but saw shape: ] [10240]
	 [[{{node generator/rnn/Assert/Assert}}]]
	 [[recovery_1/fully_connected/Sigmoid/_1901]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main_timegan.py", line 194, in <module>
    ori_data, generated_data, metrics = main(args)
  File "main_timegan.py", line 94, in main
    generated_data = timegan(ori_data, parameters, 'models', 'models', 100)
  File "/scratch/lustre/home/dopu7482/TimeGAN/timegan.py", line 330, in timegan
    generated_data_curr = sess.run(X_hat, feed_dict={Z: Z_mb, X: ori_data, T: ori_time})    
  File "/scratch/lustre/home/dopu7482/miniconda3/envs/kursinis/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/scratch/lustre/home/dopu7482/miniconda3/envs/kursinis/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/scratch/lustre/home/dopu7482/miniconda3/envs/kursinis/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/scratch/lustre/home/dopu7482/miniconda3/envs/kursinis/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: assertion failed: [Expected shape for Tensor generator/rnn/sequence_length:0 is ] [1] [ but saw shape: ] [10240]
	 [[node generator/rnn/Assert/Assert (defined at /scratch/lustre/home/dopu7482/miniconda3/envs/kursinis/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
  (1) Invalid argument: assertion failed: [Expected shape for Tensor generator/rnn/sequence_length:0 is ] [1] [ but saw shape: ] [10240]
	 [[node generator/rnn/Assert/Assert (defined at /scratch/lustre/home/dopu7482/miniconda3/envs/kursinis/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]
	 [[recovery_1/fully_connected/Sigmoid/_1901]]
0 successful operations.
0 derived errors ignored.

Original stack trace for 'generator/rnn/Assert/Assert':
  File "main_timegan.py", line 194, in <module>
    ori_data, generated_data, metrics = main(args)
  File "main_timegan.py", line 94, in main
    generated_data = timegan(ori_data, parameters, 'models', 'models', 100)
  File "/scratch/lustre/home/dopu7482/TimeGAN/timegan.py", line 172, in timegan
    E_hat = generator(Z, T)
  File "/scratch/lustre/home/dopu7482/TimeGAN/timegan.py", line 131, in generator
    e_outputs, e_last_states = tf.nn.dynamic_rnn(e_cell, Z, dtype=tf.float32, sequence_length = T)
  File "/scratch/lustre/home/dopu7482/miniconda3/envs/kursinis/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/scratch/lustre/home/dopu7482/miniconda3/envs/kursinis/lib/python3.7/site-packages/tensorflow_core/python/ops/rnn.py", line 694, in dynamic_rnn
    [_assert_has_shape(sequence_length, [batch_size])]):
  File "/scratch/lustre/home/dopu7482/miniconda3/envs/kursinis/lib/python3.7/site-packages/tensorflow_core/python/ops/rnn.py", line 688, in _assert_has_shape
    " but saw shape: ", x_shape
  File "/scratch/lustre/home/dopu7482/miniconda3/envs/kursinis/lib/python3.7/site-packages/tensorflow_core/python/util/tf_should_use.py", line 198, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs))
  File "/scratch/lustre/home/dopu7482/miniconda3/envs/kursinis/lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 165, in Assert
    return gen_logging_ops._assert(condition, data, summarize, name="Assert")
  File "/scratch/lustre/home/dopu7482/miniconda3/envs/kursinis/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_logging_ops.py", line 74, in _assert
    name=name)
  File "/scratch/lustre/home/dopu7482/miniconda3/envs/kursinis/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/scratch/lustre/home/dopu7482/miniconda3/envs/kursinis/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/scratch/lustre/home/dopu7482/miniconda3/envs/kursinis/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/scratch/lustre/home/dopu7482/miniconda3/envs/kursinis/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/scratch/lustre/home/dopu7482/miniconda3/envs/kursinis/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

